version: "3"
services:
  mongodb:
    image: 'mongo:4.2'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    ports:
      - '27017-27019:27017-27019'
volumes:
  mongodata:
    driver: local
  mongoconfig:
    driver: local

